julia-actions/julia-runtest

- action.yml
- lib/main.js
- src/main.ts
Currently, when you use the `julia-runtest` action, there is no way to disable inlining when you run the package tests.
However, often you need to disable inlining in order to get accurate code coverage information.
This pull request adds the `inline` input to the `julia-runtest` action. The default value is `yes`. Whatever value you provide is passed as the `--inline` flag to the Julia process that runs `Pkg.test`.
> Add `inline` input

- action.yml
Occasionally, there are rather large delays (> a few hours) between the time a package is registered in General and propagated to pkg.julialang.org:
* https://github.com/JuliaLang/Pkg.jl/issues/2011
* https://github.com/JuliaRegistries/General/issues/16777
* https://github.com/JuliaPackaging/PkgServer.jl/issues/60
We can avoid this problem by manually cloning `~/.julia/registries/General/` in Julia 1.5 and later (as suggested by @StefanKarpinski https://github.com/JuliaLang/Pkg.jl/issues/2011#issuecomment-689636753).
See https://github.com/tkf/Baselet.jl/pull/16 for an example of tests run by using this branch. You can see that https://github.com/JuliaRegistries/General.git is cloned with this PR: https://github.com/tkf/Baselet.jl/pull/16/checks?check_run_id=1092477889#step:4:4 while Pkg …
> Avoid delay after package registration by cloning General

- action.yml
This is useful, because JuMP runs the tests with `--depwarn=error`: 
https://github.com/jump-dev/JuMP.jl/blob/b7605dd6330aa868e21ac606e7956e9bfcea41df/.travis.yml#L31
> Enable depwarn input option

- action.yml
There's no need to have an environment variable, just allow passing a custom
project to `--project`.
Closes #22
> Add project input option

- README.md
- action.yml
This allows inserting commands like xvfb-run in front of the Julia command
(fixes #3)
---
I don't know how xvfb-run works, this implements the solution from #3. I'd appreciate it if someone who needs this feature could do a test build to verify that it works. (Change `uses: julia-actions/julia-runtest@v1` to `uses: julia-actions/julia-runtest@prefix` on a branch of your project to do that).
---
(cc @colinxs)
> Add prefix input

- LICENSE
- action.yml
- autodetect-dependabot.jl
- kwargs.jl
This should not be merged until https://github.com/JuliaLang/Pkg.jl/pull/2439 is merged.
> Add the `force_latest_compatible_version` input, and add the "auto-detect Dependabot/CompatHelper" functionality

- kwargs.jl
Before this PR:
- We check that the version number is at least `v"1.7.0-"`
After this PR:
- We check that the version number is at least `v"1.7.0-"`
- We check that the `Pkg.test` function accepts the `force_latest_compatible_version` kwarg
This is a more robust way of making sure that the `force_latest_compatible_version` feature is supported.
> Make sure that the `Pkg.test` function accepts the `force_latest_compatible_version` kwarg

- README.md
The `julia-arch` option isn't actually used to choose the architecture of Julia in the `setup-julia` step.
> Fix setup-julia example in README

- action.yml
- kwargs.jl
I believe this command option is a bit more complicated than setting `--check-bounds` to yes (force always) or no (force never), because the default state is a 3rd state where `--check-bounds` is omitted entirely, and bounds checking is done per code decisions.. It'd be good if someone could confirm my understanding on that though.. the code is a bit hard to follow.
This is untested. I've not figured out how to test this in an action yet
> Allow control of --check-bounds command option

- README.md
This way it doesn't spawn 2 test runs for each architecture on pull requests
> prevent double tests

- action.yml
This makes it easier to debug complex workflows by printing the Julia command that is actually being run after filling in all the arguments and inputs.
Merge after #71.
See https://github.com/julia-actions/Example.jl/actions/runs/3866748151/jobs/6591076864
```
env:
ANNOTATE: false
COVERAGE: true
FORCE_LATEST_COMPATIBLE_VERSION: auto
CHECK_BOUNDS: yes
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/c73a75ef-317c-4b80-a5f9-07f560a17540.sh
##[debug]The following Julia command will be executed: xvfb-run -a -s -screen 0 1024x768x24 julia --color=yes --depwarn=yes --inline=yes --project=@. -e include(joinpath(ENV["GITHUB_ACTION_PATH"], "test_harness.jl"))
```
> Print executed command in debug mode

- test_harness.jl
#79 introduced a version requirement for annotations for installing the dependencies but not for the code that adds the annotations, resulting in a dependency error for certain versions.
Fixes #80
> Add missing version check to test_harness

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/test_logger_ci.yml
> Enable Dependabot

- action.yml
- test_harness.jl
Let's you specify whether modules should be compiled during tests.
c.f. https://github.com/beacon-biosignals/StableHashTraits.jl/issues/40
> enable julia arg `--compiled-modules` during testing

- README.md
Based on a comment https://github.com/JuliaLang/IJulia.jl/pull/1103#discussion_r1491816644.
> Use `julia-actions/cache` in README example

- action.yml
- kwargs.jl
- test_harness.jl
closes https://github.com/julia-actions/julia-runtest/issues/83
> Support specifying `allow_reresolve`

- test_harness.jl
Closes https://github.com/JuliaLang/Pkg.jl/issues/3944
Hides all of this unnecessary stack trace info
> hide the harness stack trace on failure

- README.md
- action.yml
- kwargs.jl
- test_harness.jl
This PR aims at increasing flexibility for running Julia tests. The string value of the new test_arg input is passed to test and can be accessed in Julia via the ARGS variable. 
Use cases are, for example, distinuishing runs of fast and slow tests.
> Add test_arg input and populate to test_args in test()

- README.md
- Replace versions `1.6` and `nightly` with the new `lts` and `pre` keywords
- Bump versions of `setup-julia` and `cache` actions
> Update example workflow in README

- test_harness.jl
Can be seen here: https://github.com/IanButterworth/SimpleLooper.jl/actions/runs/11406030258/job/31741980077?pr=5#step:6:43
cc. @Seelengrab
> add a reproducer header

- README.md
- action.yml
- kwargs.jl
- test_harness.jl
Passing multiple `test_args` is a feature in `Pkg.test` but the action input `test_args`added in #73 allows only a single argument.
Parsing the `test_args` with julia is added to allow passing multiple args in `test_args` (as in https://github.com/julia-actions/julia-runtest/pull/73#issuecomment-2239480340)
Usage example m-fila/Example.jl#1 and CI check https://github.com/m-fila/Example.jl/pull/1/checks#step:6:61
Closes #47
> allow passing multiple arguments in test_args

- kwargs.jl
Otherwise you get the empty kwarg entry `test_args=String[]`
```
│
│ To reproduce this CI run locally run the following from the same repository state on julia version 1.10.5:
│
│ `import Pkg; Pkg.test(;coverage=true, julia_args=["--check-bounds=yes", "--compiled-modules=yes"], test_args=String[], force_latest_compatible_version=false, allow_reresolve=true)`
│
```
> don't set test_args if empty

- .github/workflows/ci.yml
- .github/workflows/test_logger_ci.yml
As per this suggestion: https://github.com/julia-actions/julia-runtest/pull/130#issuecomment-2499351493
> Use `julia-actions/cache` for tests
